[package]
name = "flogging"
version = "0.3.0"
edition = "2024"
description = "Just another [...] logger. This one loosely based on the Java logging package: java.util.logging."
license = "GPL-3.0-or-later"


[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["std","alloc"] }
