[book]
authors = ["Bradley Willcott"]
language = "en"
src = "src"
title = "The FLogging Guide"
description = ""

[rust]
edition = "2024"

[build]
build-dir = "../docs"
# create-missing = false

[output.html]
no-section-label = true
input-404 = "404.md"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[preprocessor.external-links]

[preprocessor.pagetoc]
