[book]
authors = ["Bradley Willcott"]
language = "en"
src = "src"
title = "The FLogging Guide"
description = ""

[build]
build-dir = "../docs"
# create-missing = false

[output.html]
no-section-label = true
input-404 = "404.md"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[preprocessor.external-links]

[preprocessor.pagetoc]
